version: '3'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - src/config/.env
    entrypoint: [ "minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data" ]
    networks:
      - mlops_e2e

  mysql-db:
    image: mysql:8.2
    env_file:
      - src/config/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - mlops_e2e

  zenml-server:
    image: zenmldocker/zenml-server:latest
    ports:
      - "8080:8080"
    env_file:
      - src/config/.env
    depends_on:
      - mysql-db
      - minio
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mlops_e2e

  mlflow-server:
    build:
      dockerfile: docker/Dockerfile.mlflow
    env_file:
      - src/config/.env
    depends_on:
      - mysql-db
      - minio
    ports:
      - "5001:5000"
    command: "mlflow server --app-name basic-auth --serve-artifacts"
    extra_hosts:
      - "host.docker.internal:host-gateway"



volumes:
  minio_data: { }
  mysql_data: { }

networks:
  mlops_e2e:
